### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by Jiachang-Cai** [anshengme/sentry-dingding#1]
![image](https://user-images.githubusercontent.com/8606851/43709414-5b6f23b2-999f-11e8-96fc-e144c2a5bfd5.png)

**Comment by NullYing** [comment]
issue上的坑我都踩了，坑

**Comment by NullYing** [comment]
看我PR  https://github.com/anshengme/sentry-dingding/pull/3

**Comment by NullYing** [comment]
放弃了，建议各位用这个插件

https://github.com/L3T/sentry-dingding

**Comment by zming** [comment]
https://github.com/L3T/sentry-dingding这个和ansheng有区别？

**Comment by NullYing** [comment]
作者功能写了一半，半成品

**Comment by zming** [comment]
这样，我是用docker compose部署的，在requirements写如sentry-dingding~=0.0.1，然后我看L3T里面写的安装方式是pip install sentry-dingding，感觉是没什么区别呢？

**Comment by zming** [comment]
或者说我现在就是pip install sentry-dingding，也报了这个错误

**Comment by NullYing** [comment]
用pip install git+https安装，pip install sentry-dingding是安装了这个插件的，我就是跳了这个坑

**Comment by NullYing** [comment]
简而言之，就是sentry调用notify_users去发送通知给用户，这个插件的功能就是实现这个函数，来发送dingiding的请求，然而这个库的作者，没有实现notify_users这个函数，所以会报错

**Comment by zming** [comment]
哦哦，厉害，我是通过docker compose安装部署的，如何重新安装这个包呢，我直接进onpremise_cron_1安装是不行的，估计要重新编译

**Comment by zming** [comment]
或者说之前我是写入requirements.txt文件部署的，现在应该如何部署呢sentry-dingding=0.1.2版本

**Comment by NullYing** [comment]
修改Dockerfile
在最下面增加
```Dockerfile
# 安装钉钉插件
RUN pip install git+https://github.com/L3T/sentry-dingding.git
```
然后重新build

**Comment by zming** [comment]
可以，结合了你在https://github.com/L3T/sentry-dingding写的issue。
赞👍

**Comment by 274965278** [comment]
你好，我安装了这个插件pip install git+https://github.com/L3T/sentry-dingding.git
但是我手动测试Test Plugin的时候是可以报警的
但是程序触发的时候不能报警，不知道什么原因，望高手指点
QQ 274965278

**Comment by wearetvxq** [comment]
> 274965278

我也是这样 请问您最后解决了吗?
