### ISSUE TITLE
sentry里面name不会更新

### ISSUE THREAD

**Issue by Tindtily** [anshengme/sentry-dingding#11]
https://github.com/anshengme/sentry-dingding/blob/5356f5bc9d894fe20d5bb1ff5c9c2e18ae5e6805/src/sentry_dingding/plugin.py#L53

当我修改了sentry中project的名字时，实际上是修改的slug，不是name，但是这里代码使用的是name，导致钉钉通知时，作品名一直是最初的name值

**Comment by anshengme** [comment]
晚上回去更新一波

**Comment by 0xhhhhh** [comment]
已更新至0.0.3版本
