### ISSUE TITLE
钉钉推送失败

### ISSUE THREAD

**Issue by china-enoch** [anshengme/sentry-dingding#17]
为什么我在测试都是可以的，但是在本地触发错误，sentry 都接受到了错误消息，而钉钉就没有推送消息呢？我 sentry 的版本是9.1.2

![image](https://user-images.githubusercontent.com/16871710/67620465-ca28b300-f839-11e9-9e9d-7d7a0b669726.png)

![image](https://user-images.githubusercontent.com/16871710/67620454-8fbf1600-f839-11e9-9fbb-e24aa09446d6.png)

**Comment by dotview** [comment]
搞定了么？是Sentry版本问题么？

**Comment by china-enoch** [comment]
> 搞定了么？是Sentry版本问题么？

并没有，放弃了这个插件，毕竟不是官方推荐的。利用 WebHooks 写了触发钉钉的消息。但 WebHooks 也有点儿问题，就是同一个消息如果频繁触发的话，那钩子只会触发一次。很烦。现在没有再仔细查看了。

**Comment by dotview** [comment]
> > 搞定了么？是Sentry版本问题么？
> 
> 并没有，放弃了这个插件，毕竟不是官方推荐的。利用 WebHooks 写了触发钉钉的消息。但 WebHooks 也有点儿问题，就是同一个消息如果频繁触发的话，那钩子只会触发一次。很烦。现在没有再仔细查看了。

1、进入Sentry容器一下日志没有报错;
2、进到worker容器发现并没有dingding插件的消息发送，sentry plugins list
3、在worker下安装此插件，然后重启
4、问题解决

**Comment by yangjjfc** [comment]
怎么解决的,也遇到了这个问题

**Comment by china-enoch** [comment]
> 怎么解决的,也遇到了这个问题

参考一下楼上点赞的方案。我之前是安装错容器了。

**Comment by wusb** [comment]
新版钉钉webhook调用需要设置安全模式，一般都会选择设置关键字。没有经验的话 一般很难预测错误的关键字。可以通过[阅读源码](https://github.com/anshengme/sentry-dingding/blob/master/src/sentry_dingding/plugin.py#L55)的方式了解到，消息一定是以`New alert from`开头的，所以设置其中一个就好，我选取的是`alert`，这样就能收到通知了。
