### ISSUE TITLE
Test Plugin按钮能够跑通，但是项目报错时钉钉没有反应

### ISSUE THREAD

**Issue by Liubasara** [anshengme/sentry-dingding#24]
![image](https://user-images.githubusercontent.com/24971070/76277423-a84d3b80-62c3-11ea-9530-2164024cce69.png)
点击 Test Plugin按钮时钉钉可以收到示例消息，但是在项目报错时没有收到钉钉消息。确认过应该不是项目的问题，邮件是可以收到的。自己尝试 Debug 后发现项目报错时并没有进入到 notify_users 方法中。请问是否写法发生了变化？我应该改动哪里？
![image](https://user-images.githubusercontent.com/24971070/76277517-ee0a0400-62c3-11ea-80fa-09690c8c180d.png)

**Comment by Liubasara** [comment]
我的项目是 RN 和 Vue，两个项目试过了都是相同的问题。

**Comment by Liubasara** [comment]
解决了，是我的 Sentry 版本有问题。
10.0.0 版本的 Sentry 有插件 WebHook 无法触发的 Bug，可以通过 cherry-pick 这个 bugfix 来解决。
[aa79f8b](https://github.com/getsentry/onpremise/commit/aa79f8baf9478be1340e6ef27cbb716969f303ff)

**Comment by shiyongjason** [comment]
怎么解决的

**Comment by myzhoulang** [comment]
@Liubasara 那个 docker-compose.yml 的内容和你链接中的一样 但是还是不能通知到钉钉
