### ISSUE TITLE
钉钉群通知关键字

### ISSUE THREAD

**Issue by wangjianweiwei** [anshengme/sentry-dingding#26]
需要设置下面的东西， 消息才能进去，这个可以设置嘛
![image](https://user-images.githubusercontent.com/41533289/80458065-d44f7980-8962-11ea-9a38-ec6f8bdc0811.png)

**Comment by Programmeryong** [comment]
我是直接设置alert...这样通知就可以全部获取，自定义的话，还是要看源码里面的内容进行修改

**Comment by wangjianweiwei** [comment]
@Programmeryong 你说的`直接设置alter`是啥意思，没有明白，还请解释，谢谢

**Comment by Programmeryong** [comment]
> @Programmeryong 你说的`直接设置alter`是啥意思，没有明白，还请解释，谢谢
就是添加多几个关键字...error alert new等等

**Comment by bjddd192** [comment]
keywords：sentry
