### ISSUE TITLE
安装插件成功后sentry集成里找不到dingding插件

### ISSUE THREAD

**Issue by tengzhexiao** [anshengme/sentry-dingding#4]
sentry8.22.0 pip install sentry-dingding完成了，但项目配置集成里找不到该插件。

**Comment by 0xhhhhh** [comment]
9.0.0测试没有问题，没有尝试过8.x

**Comment by arunfung** [comment]
我使用docker安装的，9.0，集成中没有，packages模块里面有

**Comment by 0xhhhhh** [comment]
@arunfung 如果你是后面才安装的，需要重启下服务sentry后台才能加载出来的

**Comment by wujunze** [comment]
> 我使用docker安装的，9.0，集成中没有，packages模块里面有

你好  你怎么在docker里面安装的这个插件  @arunfung

**Comment by arunfung** [comment]
> > 我使用docker安装的，9.0，集成中没有，packages模块里面有
> 
> 你好 你怎么在docker里面安装的这个插件 @arunfung

![image](https://user-images.githubusercontent.com/13562592/72124320-4180d400-339f-11ea-8a13-cae909347238.png)
配置好然后再build
