### ISSUE TITLE
使用docker compose安装的sentry怎么安装这个插件

### ISSUE THREAD

**Issue by wujunze** [anshengme/sentry-dingding#7]
https://github.com/getsentry/onpremise   
你好 使用的这个docker-compose 安装的Sentry怎么安装插件呢

**Comment by 0xhhhhh** [comment]
参考文章：https://blog.ansheng.me/article/docker-sentry-django-email-dingtalk

**Comment by wujunze** [comment]
昨天已经安装成功了  谢谢

**Comment by wilsunson** [comment]
> 昨天已经安装成功了 谢谢

大佬怎么更新的，上面链接失效了
