### ISSUE TITLE
notify_users 方法报错

### ISSUE THREAD

**Issue by 23233** [anshengme/sentry-dingding#9]
web_1        | 13:57:37 [INFO] sentry.eventstream.base: post_process.skip.raw_event (event_id=44L)
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/project_plugin_details.py", line 56, in post
web_1        |     test_results = plugin.test_configuration(project)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/plugins/bases/notify.py", line 183, in test_configuration
web_1        |     return self.notify(notification)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/plugins/bases/notify.py", line 76, in notify
web_1        |     r.label for r in notification.rules])
web_1        | TypeError: notify_users() got an unexpected keyword argument 'triggering_rules'
web_1        | 13:57:37 [ERROR] root: Plugin(DingDing) raised an error during test

配置了access_token之后 点击测试 就报错了

**Comment by k-dylan** [comment]
我也遇到这个问题了，解决了么

**Comment by 23233** [comment]
@k-dylan  没有 自己fork一个改了一下 就行了

**Comment by shiyongjason** [comment]
> @k-dylan 没有 自己fork一个改了一下 就行了

怎么改的
